name: YAK Pro Obfuscate

on:
  push:
    branches: [ test, main ]
  workflow_dispatch:
    inputs:
      IN_FOLDER:
        required: true
        type: string
        default: 'app'
        description: Folder name that needs to be obsfucated
      MAIN_BRANCH:
        required: true
        type: string
        default: 'main'
        description: Main branch
      PUSH_TO_BRANCH:
        required: true
        type: string
        default: 'obfuscate'
        description: Push code to empty branch
      GIT_USERNAME:
        required: true
        type: string
        default: 'codeeshop-oc'
        description: Git Username
      GIT_EMAIL:
        required: true
        type: string
        default: 'github-action[bot]@users.noreply.github.com'
        description: Git Email

jobs:
  build:
    env:
      MAIN_BRANCH: 'main'
      IN_FOLDER: 'app'
      PUSH_TO_BRANCH: 'obfuscate'
      GIT_USERNAME: 'codeeshop-oc'
      GIT_EMAIL: 'github-action[bot]@users.noreply.github.com'

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Inputs from Worflow
        if: "${{ inputs.IN_FOLDER != '' }}"
        run: |
          echo IN_FOLDER="${{ inputs.IN_FOLDER }}" >> "$GITHUB_ENV"
          echo PUSH_TO_BRANCH="${{ inputs.PUSH_TO_BRANCH }}" >> "$GITHUB_ENV"
          echo GIT_USERNAME="${{ inputs.GIT_USERNAME }}" >> "$GITHUB_ENV"
          echo GIT_EMAIL="${{ inputs.GIT_EMAIL }}" >> "$GITHUB_ENV"

      - name: Init Git
        run: |
          git config --global user.name "${{ env.GIT_USERNAME }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"
          git branch -D ${{ env.PUSH_TO_BRANCH }} && git push | echo
          git checkout -b ${{ env.PUSH_TO_BRANCH }}
          git stash
          git config pull.rebase true | echo
          git pull origin ${{ env.MAIN_BRANCH }}
          git clean -f | echo
          # rm -rf ${{ env.IN_FOLDER }}-obfuscate | echo
          # git reset -- '${{ env.IN_FOLDER }}' 'app'

      - name: Install dependencies
        run: |
          git clone https://github.com/pk-fr/yakpro-po.git
          cd yakpro-po && git clone https://github.com/nikic/PHP-Parser.git --branch 4.x
          rm yakpro-po.cnf
          cd ..
          ls
          mv yakpro-po.cnf /yakpro-po
          ls
          cd yakpro-po
          
      - name: Obfuscate project
        run: |
          yakpro-po/yakpro-po.php "${{ env.IN_FOLDER }}" -o ${{ env.IN_FOLDER }}-obfuscate

      - name: Remove Git Folders
        run: |
          git rm -r --cached .

      - name: Commit obfuscated code
        run: |
          git add ${{ env.IN_FOLDER }}-obfuscate && git commit -m "YAK Pro Obfuscate"

      - name: Push obfuscated code
        run: git push --set-upstream origin ${{ env.PUSH_TO_BRANCH }} --force
