name: Auto-Approve Pull Requests from Specified Collaborator
 
on:
  pull_request:
    branches:
      - main
      - test

  workflow_dispatch:
    inputs:
      pullRequestNumber:
        description: Pull request number to auto-approve
        required: false

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Test
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}      
      run: |
        echo "$GITHUB_CONTEXT"
    
