name: build-and-merge-direct Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:  
  dependabot:
    permissions:
      contents: write      
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build      
      run: |
        # Add the command to build your dist folder here
        yarn
        yarn build
    - name: Update Git Config
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add dist
    - name: Check - Something To Commit ?
      id: verify_diff
      run: |
        git diff --quiet --staged . || echo "changed=true" >> $GITHUB_OUTPUT
    - name: Deploy
      if: steps.verify_diff.outputs.changed == 'true'
      run: |
        git commit -m "Automated deployment"
        git push
    
