name: PHP Composer

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: phpcs
      uses: codeeshop-oc/prestashop-php-cs-fixer@0.0.3
