name: Test PHP CS Fix, Push and Merge

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: codeeshop-oc/php-cs-fix-merge@1.0.1
      with: 
        github_token: ${{ github.token }}

