name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: |
        # Add the command to build your dist folder here
        npm run build
    - name: Deploy
      run: |
        git config --global user.email "github-actions[bot]@${{ github.repository_owner }}.github.io"
        git config --global user.name "github-actions[bot]"
        git add dist
        git commit -m "Automated deployment"
        git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git master
